export const CERTIFICATIONS_DATA = [
  {
    id: "ccna",
    name: "CCNA",
    fullName: "Cisco Certified Network Associate",
    issuer: "Cisco",
    issuerLogo: "Cisco",
    category: "NETWORKING",
    color: "#00D4FF",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2024",
    description: "Industry-standard networking certification validating routing & switching skills",
    clearanceLevel: "NETWORK-ALPHA"
  },
  {
    id: "cyberops",
    name: "CyberOps Associate",
    fullName: "Cisco Certified CyberOps Associate",
    issuer: "Cisco",
    issuerLogo: "Cisco",
    category: "CYBERSECURITY",
    color: "#7B00FF",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2024",
    description: "Security operations center skills & cybersecurity fundamentals",
    clearanceLevel: "CYBER-BRAVO"
  },
  {
    id: "network-defense",
    name: "Network Defense",
    fullName: "Cisco Network Defense Essentials",
    issuer: "Cisco",
    issuerLogo: "Cisco",
    category: "SECURITY",
    color: "#00FFD1",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2023",
    description: "Network security defense mechanisms & threat mitigation",
    clearanceLevel: "DEFENSE-CHARLIE"
  },
  {
    id: "fortigate",
    name: "FortiGate 7.4 Operator",
    fullName: "FortiGate 7.4 Operator — Fortinet Certified",
    issuer: "Fortinet",
    issuerLogo: "Fortinet",
    category: "FIREWALL",
    color: "#E23636",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2024",
    description: "FortiGate firewall deployment, policy configuration & troubleshooting",
    clearanceLevel: "FIREWALL-DELTA"
  },
  {
    id: "iso27001",
    name: "ISO/IEC 27001 Associate™",
    fullName: "ISO/IEC 27001 Information Security Associate",
    issuer: "PECB",
    issuerLogo: "PECB",
    category: "COMPLIANCE",
    color: "#FFD700",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2024",
    description: "Information security management systems & compliance auditing",
    clearanceLevel: "COMPLIANCE-ECHO"
  },
  {
    id: "python-essentials",
    name: "Python Essentials 1",
    fullName: "Python Essentials 1 — Cisco Networking Academy",
    issuer: "Cisco NetAcad",
    issuerLogo: "Cisco",
    category: "PROGRAMMING",
    color: "#3776AB",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2023",
    description: "Python programming fundamentals & automation for networks",
    clearanceLevel: "CODE-FOXTROT"
  },
  {
    id: "crpo",
    name: "CRPO Certification",
    fullName: "Certified Red Team Professional Operations",
    issuer: "Cyber Security",
    issuerLogo: "CRPO",
    category: "RED TEAM",
    color: "#00D4FF",
    verifyUrl: "https://www.credly.com/users/pemaraj-manojan",
    verified: true,
    date: "2024",
    description: "Red teaming methodologies & offensive security operations",
    clearanceLevel: "RED-GOLF"
  },
  {
    id: "mcse",
    name: "Master MCSE: Windows Server 2022",
    fullName: "Master Microsoft Certified Systems Engineer — Win Server 2022",
    issuer: "Udemy",
    issuerLogo: "Udemy",
    category: "SYSTEMS",
    color: "#A435F0",
    verifyUrl: "https://www.udemy.com/user/pemaraj-manojan-4/",
    verified: true,
    date: "Mar 2025",
    description: "Advanced Windows Server administration mastery — AD, DNS, GPO, Failover",
    clearanceLevel: "SYSTEMS-HOTEL"
  }
];
